parse:
  image: node:6.7.0
  entrypoint: ./entrypoint.sh
  working_dir: /usr/src/app/
  command: npm start
  volumes:
    - ./node_modules:/usr/src/node_modules
    - ./parse:/usr/src/app
  ports:
    - 1337:1337
  links:
    - mongodb
  environment:
    - NODE_PATH:/usr/src/node_modules
    - DATABASE_URI=mongodb://mongodb:27017/dev
    - APP_ID=myAppId
    - MASTER_KEY=myMasterKey
    - PARSE_MOUNT=/api
    - PORT=1337
    - SERVER_URL=http://parse:1337/api
    - VIRTUAL_HOST=parse.app

graphql:
  image: node:6.7.0
  entrypoint: ./entrypoint.sh
  working_dir: /usr/src/app/
  command: npm start
  volumes:
    - ./node_modules:/usr/src/node_modules
    - ./graphql:/usr/src/app
  ports:
    - 1338:1338
  links:
    - parse
  environment:
    - NODE_PATH:/usr/src/node_modules
    - API_URL=http://parse:1337/api/classes
    - APP_ID=myAppId
    - MASTER_KEY=myMasterKey
    - PORT=1338
    - VIRTUAL_HOST=graphql.app

mongodb:
  image: mongo
  ports:
    - "27017:27017"
    - "28017:28017"
  command: mongod --rest
  volumes:
    - ./mongo/db:/data/db
  environment:
    - VIRTUAL_HOST=mongodb.app

nginx:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  ports:
    - "80:80"
    - "443:443"
