parse:
  image: node:6.7.0
  command: npm start
  entrypoint: ./entrypoint.sh
  volumes:
    - ./parse:/usr/src/app
  working_dir: /usr/src/app/
  ports:
    - 1337:1337
  links:
    - mongodb
  environment:
    - DATABASE_URI=mongodb://mongodb:27017/dev
    - APP_ID=myAppId
    - MASTER_KEY=myMasterKey
    - PARSE_MOUNT=/

mongodb:
  image: mongo
  ports:
    - "27017:27017"
    - "28017:28017"
  command: mongod --rest
  volumes:
    - ./mongo/db:/data/db
