
parse:
  build: parse
  working_dir: /usr/src/app/
  volumes:
    - ./parse:/usr/src/app
  ports:
    - 1337:1337
  links:
    - mongodb
  environment:
    - PARSE_SERVER_DATABASE_URI=mongodb://mongodb:27017/dev
    - PARSE_SERVER_APPLICATION_ID=myAppId
    - PARSE_SERVER_MASTER_KEY=myMasterKey
    - PARSE_SERVER_MOUNT_PATH=/api
    - PARSE_SERVER_CLOUD_CODE_MAIN=main.js
    - PORT=1337
    - PARSE_SERVER_URL=http://parse.app/api
    - VIRTUAL_HOST=parse.app

parse-e:
  image: node:6.7.0
  entrypoint: ./entrypoint.sh
  working_dir: /usr/src/app/
  command: npm start
  volumes:
    - ./node_modules:/usr/src/node_modules
    - ./parse-express:/usr/src/app
  ports:
    - 1336:1336
  links:
    - mongodb
  environment:
    - NODE_PATH:/usr/src/node_modules
    - DATABASE_URI=mongodb://mongodb:27017/dev
    - APP_ID=myAppId
    - MASTER_KEY=myMasterKey
    - PARSE_MOUNT=/api
    - PORT=1336
    - SERVER_URL=http://parse-e.app/api
    - VIRTUAL_HOST=parse-e.app

graphql:
  image: node:6.7.0
  entrypoint: ./entrypoint.sh
  working_dir: /usr/src/app/
  command: npm start
  volumes:
    - ./node_modules:/usr/src/node_modules
    - ./graphql:/usr/src/app
  ports:
    - 1338:1338
  links:
    - parse
  environment:
    - NODE_PATH:/usr/src/node_modules
    - API_URL=http://parse:1337/api/classes
    - APP_ID=myAppId
    - MASTER_KEY=myMasterKey
    - PORT=1338
    - VIRTUAL_HOST=graphql.app

dashboard:
  build: dashboard
  working_dir: /usr/src/app/
  # command: parse-dashboard
  command: parse-dashboard --config dashboard-config.json
  volumes:
    - ./dashboard:/usr/src/app
  ports:
    - 1339:1339
  links:
    - parse
  environment:
    - PORT=1339
    - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1
    # - PARSE_DASHBOARD_SERVER_URL=http://parse:1337/api
    # - PARSE_DASHBOARD_APP_NAME=Parse FTW
    # - PARSE_DASHBOARD_MASTER_KEY=myMasterKey
    # - PARSE_DASHBOARD_APP_ID=myAppId
    # - PARSE_DASHBOARD_USER_ID=root
    # - PARSE_DASHBOARD_USER_PASSWORD=parse
    - VIRTUAL_HOST=dashboard.app

mongodb:
  image: mongo
  ports:
    - "27017:27017"
    - "28017:28017"
  command: mongod --rest
  volumes:
    - ./mongo/db:/data/db
  environment:
    - VIRTUAL_HOST=mongodb.app

mongoadmin:
  image: mongo-express
  ports:
    - 8081:8081
  links:
    - mongodb
  environment:
    - VIRTUAL_HOST=admin.mongodb.app


nginx:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  ports:
    - "80:80"
    - "443:443"
